### PR TITLE
[release-ocm-2.9] MGMT-16370: fix golangci-lint failing to be pulled

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by adriengentil** [comment]
/override ci/prow/e2e-ai-operator-ztp ci/prow/format-check ci/prow/images ci/prow/lint ci/prow/mce-images ci/prow/unit-test

**Comment by adriengentil** [comment]
/override ci/prow/e2e-ai-operator-ztp ci/prow/format-check ci/prow/images ci/prow/lint ci/prow/mce-images ci/prow/unit-test

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
