### PR TITLE
MGMT-4179 Fix installer handling of ignitions to support multiple ver…

### PR DESCRIPTION
**Pull request by tsorya**
…sions

### CODE REVIEW

**Comment by filanov** [comment]
Do you need to run `go mod tidy`?

**Comment by tsorya** [comment]
> Do you need to run `go mod tidy`?

current version matches our needs but sure i can

**Comment by tsorya** [comment]
we use latest in installer, it was already "tidied"

**Review by filanov — APPROVED** [review]

**Review by ronniel1 — APPROVED** [review]
/lgtm

**Pull request merged**
