### PR TITLE
CORS-2750: Move to rhel9, decouple from cli image

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by joepvd** [comment]
/hold
brew is not ready yet to build this component on rhel9

**Comment by ashwindasr** [comment]
Test builds failed:

ose-agent-installer-csr-approver: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=58229540
ose-agent-installer-orchestrator: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=58229542

against config: https://github.com/openshift-eng/ocp-build-data/compare/openshift-4.16...ashwindasr:ocp-build-data:test-rhel9-assisted-service

**Comment by joepvd** [comment]
/unhold
Successful test build with this PR and https://github.com/openshift/assisted-installer/pull/760 and https://github.com/openshift-eng/ocp-build-data/pull/4659:
- [ose-agent-installer-api-server-container-v4.16.0-202404150400.p0.g4f6d88c.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003105)
- [ose-agent-installer-csr-approver-container-v4.16.0-202404150400.p0.gd8dd7cb.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003104)

**Comment by carbonin** [comment]
If it's been tested in brew I'm assuming the required downstream changes have been made, removing the label.

**Comment by joepvd** [comment]
The test error _might_ have to do with [this comment](https://github.com/openshift/assisted-service/pull/5792#issuecomment-1989399280). Think we'd need to override the tests on both.

**Comment by zaneb** [comment]
/retest
CI was failing due to https://issues.redhat.com/browse/OCPBUGS-32331

**Pull request merged**
