### PR TITLE
MGMT-3692 Remove assisted-installer timeout while waiting for network…

### PR DESCRIPTION
**Pull request by tsorya**
… type

### CODE REVIEW

**Comment by filanov** [comment]
It's just a patch it's not a real solution, increasing the timeout will solve the issue. 
You need to have a timeout until hosts pull the ignition and a different timeout until you are able to connect.

**Comment by tsorya** [comment]
i just remove timeout from installer, it is not relevant to service right now

**Review by filanov — APPROVED** [review]

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Pull request merged**
