### PR TITLE
MGMT-2629 - No longer printing pull secrets

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Review by ronniel1 — COMMENTED** [review]
Very impressive solution @omertuc 
Maybe worth putting this in a common place for all the services to use.
I think that assisted-service/pkg directory is used by all other repos.
@filanov what do you think?

Make sure it has extensive UT.
Also worth checking what happens if there are nested structs.

**Comment by omertuc** [comment]
> Make sure it has extensive UT.
Will add some tests

> Also worth checking what happens if there are nested structs.
It works for nested structs (if the field is another struct it recurses) but I'm not sure how it'll behave with pointers to structs, I'll check

**Comment by filanov** [comment]
> Very impressive solution @omertuc
> Maybe worth putting this in a common place for all the services to use.
> I think that assisted-service/pkg directory is used by all other repos.
> @filanov what do you think?
> 
> Make sure it has extensive UT.
> Also worth checking what happens if there are nested structs.

Agree with @ronniel1

**Comment by omertuc** [comment]
Okay so I will move this PR to the assisted-service repo

**Comment by filanov** [comment]
@omertuc the usage is good, the common part should move into assited-service repo.

**Comment by omertuc** [comment]
> @omertuc the usage is good, the common part should move into assited-service repo.

Right. I'll reopen after the other PR is merged and I modify this PR accordingly

**Comment by omertuc** [comment]
assisted-service PR https://github.com/openshift/assisted-service/pull/653

**Pull request closed without merging**
