### PR TITLE
MGMT-9358: update containers golang version to 1.17

### PR DESCRIPTION
**Pull request by filanov**
This is the first step before updating assisted-service client and
models
Step two will be to update release repo and then update the code to
import the new client.

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by filanov** [comment]
failed on gather
```
************ baremetalds assisted gather command ************
Could not create directory '/.ssh'.
ipi-ci-op-0g5v5mnr-91f17-1503400084186861568
### Gathering logs...
Could not create directory '/.ssh'.
+ cd /home/assisted
bash: line 3: cd: /home/assisted: No such file or directory
### Downloading logs...
Could not create directory '/.ssh'.
+ cd /home/assisted
bash: line 2: cd: /home/assisted: No such file or directory
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-14T17:04:47Z"}
error: failed to execute wrapped command: exit status 1
```

**Comment by filanov** [comment]
/test e2e-metal-assisted
```
Job execution failed: Pod pending timeout.
```

**Pull request merged**
