### PR TITLE
MGMT-12467: Remove special handling for installing OCP < 4.7

### PR DESCRIPTION
**Pull request by eranco74**
This means that the installer will no longer support installing OCP-4.6

### CODE REVIEW

**Comment by tsorya** [comment]
we don't support anymore?

**Comment by eranco74** [comment]
> we don't support anymore?

We don't support 4.6 for some time now

**Comment by omertuc** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-installer/571/pull-ci-openshift-assisted-installer-master-edge-e2e-metal-assisted/1589605995233939456

[Seen this before](https://coreos.slack.com/archives/C014N2VLTQE/p1666779495723009?thread_ts=1666762738.197869&cid=C014N2VLTQE)

**Comment by eranco74** [comment]
Seems like ingress wasn't happy
```
Unable to apply 4.12.0-0.nightly-2022-11-06-054655: Cluster operator ingress is degraded'
```
@omertuc looks like ingress is spinning a new router every few seconds, where did you see it before?
Looks like a bug in 4.12 nightly

**Comment by eranco74** [comment]
> /lgtm

prow wake up!!

**Pull request merged**
