### PR TITLE
NO-ISSUE Use errors.Wrap instead of creating a new error

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by YuviGold** [comment]
Since you made a branch and not a fork you triggered `continuous-integration/jenkins/branch` that failed.
Either make it pass or create a fork to avoid it.

Holding to stop the spamming.
/hold

**Comment by eranco74** [comment]
> Since you made a branch and not a fork you triggered `continuous-integration/jenkins/branch` that failed.
> Either make it pass or create a fork to avoid it.
> 
> Holding to stop the spamming.
> /hold

Thanks

**Pull request merged**
