### PR TITLE
NO-ISSUE: controller logs optimizations

### PR DESCRIPTION
**Pull request by tsorya**
NO-ISSUE: In case upload of must-gather fails we need to retry to upload
    and not to gather it one more time as it has less chance to succeed
    In case pod name doesn't exist add one in order to upload file
NO-ISSUE: Adding log operator status conditions

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by omertuc** [comment]
[Note that this caused a regression in signature behavior](https://github.com/openshift-assisted/assisted-installer-deployment/pull/387)

**Pull request merged**
