### PR TITLE
MGMT-12115: Fix wrong formatting in Controller Pod definition

### PR DESCRIPTION
**Pull request by mkowalski**
Fixes: #551
Contributes-to: [MGMT-12115](https://issues.redhat.com//browse/MGMT-12115)

### CODE REVIEW

**Comment by vrutkovs** [comment]
Lets wait for https://github.com/openshift/release/pull/32564 and run ztp test here?
/hold

Feel free to remove if release PR gets stuck or we want to fast-track this

**Comment by mkowalski** [comment]
Good for me, no rush, let's test that if we can get the CI job easily

**Comment by mkowalski** [comment]
/unhold

Let's go

**Pull request merged**
